## Git workflow to copy secrets from one to anothet KV across the subscriptions
## The service principal used should have access to both the subscriptions
name: Copy KV secrets Across subscriptions
permissions:
  content: read
  pull-requests:write
on:
  workflow_dispatch
    inputs:
      source_keyvault:
        description: "Source KV"
        required: true
        value: "source kv name"
      destination_keyvault:
        description: "Dest KV"
        required: true      
        value: "destination kv name"
jobs:
  copy-secrets:
    runs-on: [agent-for-workflow-execution]
    steps:
      - name: Azure login (Source Subscription)
        uses: azure/login@v1
        with
          creds: ${{ secrets.Azure_Creds_Source }}
      - name: Fetch secret from Source KV & Copy to Dest KV
        id: fetch_secrets
        env:
          SOURCE_KV: ${{ github.event.inputs.source_keyvault }} 
          DEST_KV: ${{ github.event.inputs.destination_keyvault }}
        run: |
         echo "listing all secrets in KV: "$SOURCE_KV""
         listsecrets=$(az keyvault secret list --vault-name "$SOURCE_KV" --output table)
         echo "Secrets in keyvault: $listsecrets"
         SRC_SECRET_COUNT=$(az keyvault secret list --valut-name "$SOURCE_KV" --query "length(@)" -o tsv)
         echo "Number of secrets in keyvault "$SOURCE_KV": "$SRC_SECRET_COUNT"
         secrets=$(az keyvault secret list --vault-name "$SOURCE_KV" --query "[].name" -o tsv)
         for secret_name in $(az keyvault secret list --vault-name "$SOURCE_KV" --query "[].name" -o tsv); 
         do
            secret_value=$(az keyvault secret show --vault-name "$SOURCE_KV" --name "$secret_name" --query "value" -o tsv)
            az keyvault secret set --vault-name $DEST_KV --name $secret_name --value $secret_value
            echo "Copied secret: $secret_name from $SOURCE_KV to $DEST_KV         
         done         
